<a href="https://colab.research.google.com/github/mateus-neres/projeto_de_analise_estatistica_enem_2019/blob/main/amostragem_etapa02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PROJETO DE ANÁLISE ESTATISTICA ENEM 2019**

Este projeto analisa os resultados do ENEM no estado de São Paulo no ano de 2019.

Os dados foram extraídos do site do INEP:

http://inep.gov.br/mocrodados

#**2° ETAPA: AMOSTRAGENS**

##Exportando bibliotecas

In [97]:
import pandas as pd
import numpy as np

##Importando dataframe

In [98]:
enem_sp = pd.read_csv("/content/drive/MyDrive/curso_Udemy/curso_estatistica_python/enem_2019_tratado.csv", sep = ",", encoding = "iso-8859-1")

##Exibindo colunas e linhas sem abreviações

para exibir as colunas e linhas de um DataFrame sem abreviações, você pode usar o método pd.set_option do Pandas para configurar as opções de exibição.

In [99]:
pd.set_option("display.max_columns", None)
# pd.set_option("display.max_rows", None)
# pd.set_option("display.float_format", "{:.2f}".format)

In [100]:
enem_sp.head()

INSCRICAO   MUNICIPIO_RESIDENCIA  IDADE SEXO  ESTADO_CIVIL    RACA  \
0  1,90E+11           Santa Isabel     22    M             1   parda   
1  1,90E+11              São Paulo     17    F             1   parda   
2  1,90E+11  São Bernardo do Campo     19    M             1   parda   
3  1,90E+11             Embu-Guaçu     17    F             1   parda   
4  1,90E+11              Guarulhos     23    F             1  branca   

   NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA   CO_ESCOLA  \
0              1                1  não_respondeu         NaN   
1              1                2        privada  15567761.0   
2              1                2        pública  35904958.0   
3              1                2        pública         NaN   
4              1                1  não_respondeu         NaN   

        NO_MUNICIPIO_ESC  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  \
0                    NaN               1               1               1   
1                  Belém               1               1               1   
2  São Bernardo do Campo               1               1               1   
3                    NaN               1               1               1   
4                    NaN               1               1               1   

   TP_PRESENCA_MT  NOTA_CN  NOTA_CH  NOTA_LC  NOTA_MT    LINGUA  \
0               1    564.6    585.8    592.9    600.2    inglês   
1               1    576.2    641.1    634.3    731.8    inglês   
2               1    402.2    424.8    509.6    393.2  espanhol   
3               1    399.6    426.8    487.2    419.2    inglês   
4               1    625.7    646.5    629.3    796.1    inglês   

   TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  COMP5  NOTA_REDACAO INTERNET  
0                1.0  160.0  200.0  180.0  200.0  200.0         940.0      sim  
1                1.0  160.0  120.0  200.0  200.0  200.0         880.0      não  
2                1.0   80.0  160.0  120.0  100.0  100.0         560.0      sim  
3                1.0  120.0  120.0  120.0  120.0   80.0         560.0      sim  
4                1.0  160.0  200.0  180.0  180.0  160.0         880.0      sim

#**AREA DE AMOSTRAGEM SERÁ A CIDADE DE CAMPINAS-SP**

#Criando nova tabela com a amostragem de Campinas-SP

In [101]:
enem_campinas = enem_sp.loc[enem_sp.MUNICIPIO_RESIDENCIA == "Campinas"]

In [102]:
enem_campinas.head()

INSCRICAO MUNICIPIO_RESIDENCIA  IDADE SEXO  ESTADO_CIVIL    RACA  \
15   1,90E+11             Campinas     17    F             1  branca   
31   1,90E+11             Campinas     19    F             1   parda   
51   1,90E+11             Campinas     17    F             1  branca   
116  1,90E+11             Campinas     17    F             1  branca   
169  1,90E+11             Campinas     17    M             1  branca   

     NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA   CO_ESCOLA  \
15               1                1  não_respondeu         NaN   
31               1                1  não_respondeu         NaN   
51               1                2        pública         NaN   
116              1                2        pública  26078562.0   
169              1                2        privada         NaN   

    NO_MUNICIPIO_ESC  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  \
15               NaN               1               1               1   
31               NaN               1               1               1   
51               NaN               1               1               1   
116    Lagoa do Ouro               1               1               1   
169              NaN               1               1               1   

     TP_PRESENCA_MT  NOTA_CN  NOTA_CH  NOTA_LC  NOTA_MT    LINGUA  \
15                1    422.9    496.5    509.6    496.5    inglês   
31                1    634.2    657.4    580.9     73.1    inglês   
51                1    420.3    485.6    517.4    417.5    inglês   
116               1     39.7    488.1    472.5    480.5  espanhol   
169               1    563.7    551.3    582.3    624.4    inglês   

     TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  COMP5  NOTA_REDACAO  \
15                 1.0  160.0  120.0  140.0  140.0  120.0         680.0   
31                 1.0  140.0  120.0  160.0  140.0  160.0         720.0   
51                 1.0  160.0  140.0  160.0  120.0  160.0         740.0   
116                1.0  120.0   60.0   60.0  100.0    0.0         340.0   
169                1.0  140.0  120.0  140.0  160.0  160.0         720.0   

    INTERNET  
15       sim  
31       sim  
51       sim  
116      sim  
169      sim

In [103]:
enem_campinas.shape

(13198, 28)

##*AMOSTRAGEM ALEATÓRIA SIMPLES**

Seleção execultadas por meio de sorteio sem nenhum filtro

In [104]:
np.random.seed(1) # Função seed serve para amarsenar o valor coletado aleatoriamente pelo python no valor desejado (1)

###Separando a amostra com 20% do total da tabela enem_campinas com a função .sample(frac=0.20)

In [105]:
amostra_simples = enem_campinas.sample(frac=0.20) # Porcentagem

In [106]:
amostra_simples.head(5)

INSCRICAO MUNICIPIO_RESIDENCIA  IDADE SEXO  ESTADO_CIVIL    RACA  \
327999  1,90E+11             Campinas     20    M             1   preta   
235222  1,90E+11             Campinas     17    F             1  branca   
134221  1,90E+11             Campinas     18    F             1   parda   
358407  1,90E+11             Campinas     25    M             0   parda   
173364  1,90E+11             Campinas     18    M             1   parda   

        NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA   CO_ESCOLA  \
327999              1                1  não_respondeu         NaN   
235222              1                2        pública  35018296.0   
134221              1                2        pública         NaN   
358407              1                1  não_respondeu         NaN   
173364              1                1  não_respondeu         NaN   

       NO_MUNICIPIO_ESC  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  \
327999              NaN               1               1               1   
235222         Campinas               1               1               1   
134221              NaN               1               1               1   
358407              NaN               1               1               1   
173364              NaN               1               1               1   

        TP_PRESENCA_MT  NOTA_CN  NOTA_CH  NOTA_LC  NOTA_MT    LINGUA  \
327999               1    546.8    583.5    531.5    459.6    inglês   
235222               1    551.4    603.3    590.3     48.8    inglês   
134221               1    440.2    431.3    414.4    429.9    inglês   
358407               1    567.6    549.6    551.3    687.4  espanhol   
173364               1    457.9    573.5    576.3    617.9    inglês   

        TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  COMP5  NOTA_REDACAO  \
327999                1.0  180.0  200.0  180.0  200.0  200.0         960.0   
235222                1.0  160.0  180.0  160.0  140.0  140.0         780.0   
134221                1.0  100.0  120.0  100.0   80.0  100.0         500.0   
358407                1.0  140.0  120.0  120.0  140.0  140.0         660.0   
173364                1.0  140.0  120.0  140.0  140.0   80.0         620.0   

       INTERNET  
327999      sim  
235222      sim  
134221      sim  
358407      não  
173364      sim

In [107]:
amostra_simples.shape

(2640, 28)

###Podemos também coletar uma quantidade determinada de registro apenas digitando o valor de restros que desejamos .sample(3000)

In [108]:
amostra_simples = enem_campinas.sample(3000) # Quantidade numérica

In [109]:
amostra_simples.head(5)

INSCRICAO MUNICIPIO_RESIDENCIA  IDADE SEXO  ESTADO_CIVIL     RACA  \
57191   1,90E+11             Campinas     17    F             1  amarela   
215078  1,90E+11             Campinas     17    F             1    parda   
430770  1,90E+11             Campinas     18    M             1   branca   
409180  1,90E+11             Campinas     19    F             1    preta   
429862  1,90E+11             Campinas     17    F             1   branca   

        NACIONALIDADE  TP_ST_CONCLUSAO   ESCOLA   CO_ESCOLA NO_MUNICIPIO_ESC  \
57191               1                2  pública  35045937.0         Campinas   
215078              1                2  pública  35018880.0         Campinas   
430770              1                2  privada  35112902.0         Campinas   
409180              1                2  pública  35047120.0         Campinas   
429862              1                2  pública  35812900.0         Campinas   

        TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  TP_PRESENCA_MT  \
57191                1               1               1               1   
215078               1               1               1               1   
430770               1               1               1               1   
409180               1               1               1               1   
429862               1               1               1               1   

        NOTA_CN  NOTA_CH  NOTA_LC  NOTA_MT  LINGUA  TP_STATUS_REDACAO  COMP1  \
57191      53.3    564.5    566.4    653.8  inglês                1.0  120.0   
215078    481.8     49.5    513.5    507.8  inglês                1.0  120.0   
430770    626.6    665.8    628.8    823.3  inglês                1.0  140.0   
409180    459.7    406.1    477.7    574.7  inglês                1.0  120.0   
429862    465.9    566.1    583.3    522.7  inglês                1.0  140.0   

        COMP2  COMP3  COMP4  COMP5  NOTA_REDACAO INTERNET  
57191   120.0  120.0  140.0  120.0         620.0      sim  
215078  120.0  120.0  120.0  100.0         580.0      sim  
430770  180.0  120.0  160.0  160.0         760.0      sim  
409180  120.0  120.0  120.0  140.0         620.0      sim  
429862  120.0  120.0  160.0  100.0         640.0      sim

In [110]:
amostra_simples.shape

(3000, 28)

###Outra forma de obter uma amostragem

In [111]:
np.random.seed(2)

In [112]:
amostra = np.random.choice(a=[0,1], size=13198, replace=True, p=[0.8,0.2])

In [113]:
amostra

array([0, 0, 0, ..., 0, 0, 1])

In [114]:
len(amostra[amostra == 0])

10566

In [115]:
len(amostra[amostra == 1])

2632

In [116]:
amostra_simples = enem_campinas.loc[amostra == 1]

In [117]:
amostra_simples.head(5)

INSCRICAO MUNICIPIO_RESIDENCIA  IDADE SEXO  ESTADO_CIVIL    RACA  \
949   1,90E+11             Campinas     17    F             1  branca   
1058  1,90E+11             Campinas     19    M             1   parda   
1980  1,90E+11             Campinas     17    F             1   parda   
2053  1,90E+11             Campinas     18    F             1   parda   
2328  1,90E+11             Campinas     20    F             1   parda   

      NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA   CO_ESCOLA  \
949               1                2        pública  35924573.0   
1058              1                1  não_respondeu         NaN   
1980              1                2        pública  35018302.0   
2053              1                1  não_respondeu         NaN   
2328              2                1  não_respondeu         NaN   

     NO_MUNICIPIO_ESC  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  \
949          Campinas               1               1               1   
1058              NaN               1               1               1   
1980         Campinas               1               1               1   
2053              NaN               1               1               1   
2328              NaN               1               1               1   

      TP_PRESENCA_MT  NOTA_CN  NOTA_CH  NOTA_LC  NOTA_MT    LINGUA  \
949                1    577.5    590.2    561.9    601.4    inglês   
1058               1    519.6    387.9    533.3    474.6    inglês   
1980               1    491.6    552.6    533.5    479.9    inglês   
2053               1    408.1    390.1    392.6    424.2    inglês   
2328               1    551.9    512.2    548.5    552.5  espanhol   

      TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  COMP5  NOTA_REDACAO  \
949                 1.0  160.0  120.0  120.0  140.0  120.0         660.0   
1058                1.0  120.0  120.0  120.0  160.0  100.0         620.0   
1980                1.0  120.0  120.0  120.0  140.0  120.0         620.0   
2053                1.0  100.0   40.0   20.0   80.0    0.0         240.0   
2328                1.0  120.0  120.0  100.0  100.0   80.0         520.0   

     INTERNET  
949       sim  
1058      sim  
1980      não  
2053      sim  
2328      sim

#**AMOSTRAGEM SISTEMÁTICA**

Os membros da população são ordenados numericamentes e selecionados aleatoriamente obedecendo uma ordem numérica.

In [118]:
enem_campinas.shape

(13198, 28)

In [119]:
np.random.seed(2)
inicio = np.random.choice(10,1)

In [120]:
amostra2 = np.arange(inicio,13198,100)
amostra2

array([    8,   108,   208,   308,   408,   508,   608,   708,   808,
         908,  1008,  1108,  1208,  1308,  1408,  1508,  1608,  1708,
        1808,  1908,  2008,  2108,  2208,  2308,  2408,  2508,  2608,
        2708,  2808,  2908,  3008,  3108,  3208,  3308,  3408,  3508,
        3608,  3708,  3808,  3908,  4008,  4108,  4208,  4308,  4408,
        4508,  4608,  4708,  4808,  4908,  5008,  5108,  5208,  5308,
        5408,  5508,  5608,  5708,  5808,  5908,  6008,  6108,  6208,
        6308,  6408,  6508,  6608,  6708,  6808,  6908,  7008,  7108,
        7208,  7308,  7408,  7508,  7608,  7708,  7808,  7908,  8008,
        8108,  8208,  8308,  8408,  8508,  8608,  8708,  8808,  8908,
        9008,  9108,  9208,  9308,  9408,  9508,  9608,  9708,  9808,
        9908, 10008, 10108, 10208, 10308, 10408, 10508, 10608, 10708,
       10808, 10908, 11008, 11108, 11208, 11308, 11408, 11508, 11608,
       11708, 11808, 11908, 12008, 12108, 12208, 12308, 12408, 12508,
       12608, 12708,

In [121]:
amostra_sistematica = enem_campinas.iloc[amostra2,:]

In [122]:
amostra_sistematica

INSCRICAO MUNICIPIO_RESIDENCIA  IDADE SEXO  ESTADO_CIVIL    RACA  \
401     1,90E+11             Campinas     18    F             1  branca   
5079    1,90E+11             Campinas     18    F             1  branca   
9218    1,90E+11             Campinas     19    F             1  branca   
13685   1,90E+11             Campinas     20    M             1   parda   
18239   1,90E+11             Campinas     20    M             1  branca   
...          ...                  ...    ...  ...           ...     ...   
481894  1,90E+11             Campinas     34    M             1   parda   
485805  1,90E+11             Campinas     16    F             1  branca   
488958  1,90E+11             Campinas     19    F             1  branca   
492626  1,90E+11             Campinas     21    M             1  branca   
496410  1,90E+11             Campinas     19    M             1   preta   

        NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA   CO_ESCOLA  \
401                 1                1  não_respondeu         NaN   
5079                1                2        pública  35018855.0   
9218                1                1  não_respondeu         NaN   
13685               1                1  não_respondeu         NaN   
18239               1                1  não_respondeu         NaN   
...               ...              ...            ...         ...   
481894              1                1  não_respondeu         NaN   
485805              1                2        pública  35039901.0   
488958              1                1  não_respondeu         NaN   
492626              1                1  não_respondeu         NaN   
496410              1                1  não_respondeu         NaN   

       NO_MUNICIPIO_ESC  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  \
401                 NaN               1               1               1   
5079           Campinas               1               1               1   
9218                NaN               1               1               1   
13685               NaN               1               1               1   
18239               NaN               1               1               1   
...                 ...             ...             ...             ...   
481894              NaN               1               1               1   
485805         Campinas               1               1               1   
488958              NaN               1               1               1   
492626              NaN               1               1               1   
496410              NaN               1               1               1   

        TP_PRESENCA_MT  NOTA_CN  NOTA_CH  NOTA_LC  NOTA_MT  LINGUA  \
401                  1    614.8    657.2    592.5     68.6  inglês   
5079                 1    433.1    494.7    505.1    419.9  inglês   
9218                 1    605.4    593.5    628.8    617.1  inglês   
13685                1     63.9    673.3    600.3    576.4  inglês   
18239                1    758.6    696.8    601.7    796.2  inglês   
...                ...      ...      ...      ...      ...     ...   
481894               1    719.5     65.4     64.2    932.1  inglês   
485805               1    337.4    543.9    466.5    441.6  inglês   
488958               1    444.4    505.4    577.1    492.9  inglês   
492626               1    536.5    608.5    592.4     51.1  inglês   
496410               1    457.9     58.2    518.6    404.4  inglês   

        TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  COMP5  NOTA_REDACAO  \
401                   1.0  160.0  160.0  180.0  160.0  200.0         860.0   
5079                  1.0  140.0  120.0  120.0  120.0  140.0         640.0   
9218                  1.0  120.0  120.0  120.0  120.0  120.0         600.0   
13685                 1.0  160.0  200.0  180.0  200.0  180.0         920.0   
18239                 1.0  160.0  200.0  200.0  200.0  200.0         960.0   
...                   ...    ...    ...    ...    ...    ...       

###Outra forma de obter amostra sistemática

In [123]:
np.random.seed(30)

In [124]:
inicio = np.random.choice(10,1)
passo = np.random.randint(100,150,1)

In [125]:
passo

array([137])

In [126]:
inicio

array([5])

In [127]:
amostra2 = np.arange(inicio,13198,passo)
amostra

array([0, 0, 0, ..., 0, 0, 1])

In [128]:
amostra2 = enem_campinas.iloc[amostra2,:]

In [130]:
amostra2

INSCRICAO MUNICIPIO_RESIDENCIA  IDADE SEXO  ESTADO_CIVIL    RACA  \
186     1,90E+11             Campinas     19    F             1  branca   
6519    1,90E+11             Campinas     26    M             0   preta   
12280   1,90E+11             Campinas     20    F             1  branca   
18436   1,90E+11             Campinas     22    F             2   preta   
23717   1,90E+11             Campinas     18    M             1   parda   
...          ...                  ...    ...  ...           ...     ...   
478519  1,90E+11             Campinas     23    F             1  branca   
483431  1,90E+11             Campinas     18    F             1  branca   
488340  1,90E+11             Campinas     19    F             1  branca   
493180  1,90E+11             Campinas     33    F             0  branca   
498126  1,90E+11             Campinas     17    M             1  branca   

        NACIONALIDADE  TP_ST_CONCLUSAO         ESCOLA  CO_ESCOLA  \
186                 1                1  não_respondeu        NaN   
6519                1                1  não_respondeu        NaN   
12280               1                1  não_respondeu        NaN   
18436               1                1  não_respondeu        NaN   
23717               1                1  não_respondeu        NaN   
...               ...              ...            ...        ...   
478519              1                1  não_respondeu        NaN   
483431              1                1  não_respondeu        NaN   
488340              1                1  não_respondeu        NaN   
493180              1                1  não_respondeu        NaN   
498126              1                2        privada        NaN   

       NO_MUNICIPIO_ESC  TP_PRESENCA_CN  TP_PRESENCA_CH  TP_PRESENCA_LC  \
186                 NaN               1               1               1   
6519                NaN               1               1               1   
12280               NaN               1               1               1   
18436               NaN               1               1               1   
23717               NaN               1               1               1   
...                 ...             ...             ...             ...   
478519              NaN               1               1               1   
483431              NaN               1               1               1   
488340              NaN               1               1               1   
493180              NaN               1               1               1   
498126              NaN               1               1               1   

        TP_PRESENCA_MT  NOTA_CN  NOTA_CH  NOTA_LC  NOTA_MT    LINGUA  \
186                  1    560.6    591.1     64.0    628.5    inglês   
6519                 1    518.8    589.4    533.4    364.9    inglês   
12280                1    425.3    537.7    521.8     46.7    inglês   
18436                1    397.8    419.3    464.6    586.7  espanhol   
23717                1    355.1    344.3    432.5     48.4    inglês   
...                ...      ...      ...      ...      ...       ...   
478519               1    501.8    586.3    565.8    592.2    inglês   
483431               1    480.5    583.5     56.2     55.2    inglês   
488340               1    482.4    548.2    556.3    542.3  espanhol   
493180               1    402.9    411.4    426.4    396.7    inglês   
498126               1    495.8    601.6    557.1    653.7    inglês   

        TP_STATUS_REDACAO  COMP1  COMP2  COMP3  COMP4  COMP5  NOTA_REDACAO  \
186                   1.0  120.0  120.0  120.0  120.0   80.0         560.0   
6519                  1.0  120.0  200.0  140.0  120.0  200.0         780.0   
12280                 1.0  120.0  120.0   80.0  100.0   20.0         440.0   
18436                 1.0  100.0  120.0  120.0  100.0   80.0         520.0   
23717                 1.0   80.0   80.0   80.0   80.0    0.0         320.0   
...                   ...    ...    ...    ...    ...  

#**AMOSTRAGEM ESTRATIFICADA**

Divisão da população em grupos e seleção aleatoria de uma amostra de cada grupo

#**Referências e links úteis**
**Referências Bibliográficas**

LARSON, Ron. **Estatística Aplicada.** São Paulo: Pearson Prentice Hall, 2010.

COSTA NETO, Pedro Luiz de Oliveira. **Estatística.** São Paulo: Bluncher, 2002.

MORETTIN, Luiz Gonzaga. **Estatística Básica: probabilidade e inferência.** São Paulo: Pearson Prentice Hall, 2010.



**LINKS ÚTEIS:**

**Site INEP dos microdados do ENEM:**

https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/enem

**Estatística:**

https://www.udemy.com/course/estatistica-com-linguagem-r/?referralCode=0DBFC727FE8574D5BCE8

**Graus de liberdade:**

https://pt.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/more-standard-deviation/v/another-simulation-giving-evidence-that-n-1-gives-us-an-unbiased-estimate-of-variance

**Teste de Normalidade:**

https://www.inf.ufsc.br/~vera.carmo/Testes_de_Hipoteses/Testes_aderencia.pdf

**Bibliotecas Python**

https://docs.python.org/pt-br/3/library/

https://pandas.pydata.org/docs/

https://docs.scipy.org/

https://www.anaconda.com/products/individual

**Gráficos**

https://seaborn.pydata.org/index.html

https://plotly.com/python/reference/#layout